// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Mnstr = require("../mnstr/Mnstr.bs.js");
var Config = require("../utils/Config.bs.js");

var query = Mnstr.ApiClient[/* query */8];

var mutate = Mnstr.ApiClient[/* mutate */9];

var client = Curry._3(Mnstr.ApiClient[/* make */10], Config.Api[/* endpoint */0], /* Some */[Mnstr.ClientSession[/* get */1]], /* () */0);

exports.query = query;
exports.mutate = mutate;
exports.client = client;
/* client Not a pure module */
