// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Config = require("../Config.bs.js");
var MnstrClient = require("@ecliptic/mnstr-client/src/MnstrClient.bs.js");
var MnstrClientBrowser = require("@ecliptic/mnstr-client/src/MnstrClientBrowser.bs.js");

var match = Config.Env[/* isDev */0];

var client = MnstrClient.make(/* None */0, /* Some */[MnstrClientBrowser.Session[/* get */1]], Config.Api[/* endpoint */0], /* Some */[match !== 0 ? true : false], /* () */0);

var query = MnstrClient.query;

var mutate = MnstrClient.mutate;

exports.query = query;
exports.mutate = mutate;
exports.client = client;
/* client Not a pure module */
