// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function makeMiddleware(handler) {
  return (function (store) {
      return (function (next) {
          return (function (action) {
              return Curry._3(handler, store, next, action);
            });
        });
    });
}

function handleActors(actors) {
  return makeMiddleware((function (store, next, action) {
                var dispatch = store.dispatch;
                var getState = store.getState;
                var result = next(action);
                actors.forEach((function (actor) {
                        return Curry._3(actor, action, dispatch, getState);
                      }));
                return result;
              }));
}

exports.makeMiddleware = makeMiddleware;
exports.handleActors = handleActors;
/* No side effect */
