// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Redux = require("redux");
var UserState = require("./UserState.bs.js");
var EventState = require("./EventState.bs.js");
var StateMiddleware = require("./StateMiddleware.bs.js");
var ReduxDevtoolsExtension = require("redux-devtools-extension");

function identity(a) {
  return a;
}

var rootReducer = Redux.combineReducers({
      users: UserState.reducer,
      events: EventState.reducer
    });

var store = Redux.createStore(rootReducer, ReduxDevtoolsExtension.composeWithDevTools(Redux.applyMiddleware(StateMiddleware.handleActors(/* array */[EventState.eventManagement]))));

exports.identity = identity;
exports.rootReducer = rootReducer;
exports.store = store;
/* rootReducer Not a pure module */
